environment:

  matrix:
    - python : 27
    - python : 27-x64
    - python : 34
    - python : 34-x64
    - python : 35
    - python : 35-x64

install:

  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Check that we have the expected version and architecture for Python
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Install pip
  - python -m pip install --upgrade pip

  # Install the build and runtime dependencies of the project.
  - pip install setuptools pandas six joblib pyprind py_stringmatching nose

build: false

test_script:
  # run unit tests
  - nosetests

on_success:
  - echo Build succesful!
